# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dougu',
                'doc_host': 'https://terryn.github.io',
                'git_url': 'https://github.com/terryn/dougu',
                'lib_path': 'dougu'},
  'syms': {'dougu.core': {'dougu.core.foo': ('core.html#foo', 'dougu/core.py')}}}
